/* Boot: masthead, tabs, deep links, first card. */
(function boot() {
  var M = D.meta;
  $("#mastsub").innerHTML = "<b>Substrate Corpus Catalogue</b> · " + plural(D.entries.length, "accession") + " · " + fmt(D.figures.figures.tokens) + " tokens · " +
    plural(D.register.length, "registered unit") + " · build seed " + esc(M.seed) + " · engine " + esc(M.version);
  $("#tabs").addEventListener("click", function (ev) {
    var b = ev.target.closest("button[data-v]");
    if (b) show(b.getAttribute("data-v"));
  });
  $("#tabs").addEventListener("keydown", function (ev) {
    if (ev.key !== "ArrowRight" && ev.key !== "ArrowLeft") return;
    var btns = $$("#tabs button"), i = btns.indexOf(document.activeElement);
    if (i < 0) return;
    var j = (i + (ev.key === "ArrowRight" ? 1 : btns.length - 1)) % btns.length;
    btns[j].focus(); show(btns[j].getAttribute("data-v"));
  });
  var hash = "";
  try { hash = decodeURIComponent((window.location.hash || "").slice(1)); } catch (e) { hash = ""; }
  var startSel = M.start;
  if (/^CSC-\d{4}(\.III)?$/.test(hash)) startSel = hash.replace(".III", "/III");
  else if (store.get("sel", null) && BYREF[store.get("sel", null)]) startSel = store.get("sel", null);
  show("catalogue");
  select(BYREF[startSel] ? startSel : key(D.entries[0]));
  var v = VIEWS.indexOf(hash) >= 0 ? hash : (/^CSC-/.test(hash) ? "catalogue" : store.get("tab", "catalogue"));
  if (v !== "catalogue") show(v);
  $("#foot").innerHTML = "Authority C · design proposal for approval · not canon. " +
    "Generated by the HEL engine " + esc(M.version) + " from seed " + esc(M.seed) + " on " + esc(M.built) + ": a sealed world was rendered into records, damaged by stated rules, transcribed by the 1908 committee with its known errors, and numbered in accession order. " +
    "The key that generated it is not on this page. Before publishing, the page’s data was checked against " + fmt(M.leak.needles) + " strings drawn from the sealed key — definitions, verdicts and feature names — and " +
    (M.leak.hits ? M.leak.hits + " were found." : "none was found.") + " Reproduce with <code>python3 -m hel.corpus</code> and <code>python3 tools/build_reading_room.py</code>.";
})();
